services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel-app
        container_name: laravel_app
        ports:
            - "9000:9000"
        volumes:
            - .:/var/www
        networks:
            - app-network

    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/fastcgi_params:/etc/nginx/fastcgi_params  # Добавлено
        networks:
            - app-network
        depends_on:
            - app

    mysql:
        image: mysql:latest
        container_name: mysql
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - app-network

    adminer:
        image: adminer
        container_name: adminer
        ports:
            - "8081:8080"
        networks:
            - app-network

    mailhog:
        image: mailhog/mailhog
        container_name: mailhog
        ports:
            - "1025:1025"
            - "8025:8025"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    mysql_data:
